### ISSUE TITLE
Trouble getting the example to work

### ISSUE THREAD

**Issue by Varmod** [infinitespace-studios/MauiAndroidAssetPackExample#1]
Hi, 

I'm trying to get your example running but I'm running into issues. I've tried deploying the project to an android emulator, it does some quick building but doesn't start the app. 

I've also tried porting the code to my app but that was also unsuccessful, my project builds properly but the 'Foo.txt' file is not found when I try to read it.

Any idea what I could be doing wrong?

**Comment by Varmod** [comment]
The project didn't deploy because deploying was disabled in the configuration. After running the Example I'm running into the same issue. `System.IO.FileNotFoundException: 'Foo.txt'`

@dellis1972 Any idea what could be wrong?

I've tried looking into it myself and so far I was able to confirm that `BuildAssetFeature` runs and produces a  `AssetsFeature.zip` that contains the data. However inside the binlog I couldn't find any reference to the zip later so I'm unsure yet how it's supposed to end up in the main project.

**Comment by dellis1972** [comment]
If you are trying in debug configuration it might be defaulting to `AndroidPackageFormat` = `apk` which will not work.
Try adding 

`<AndroidPackageFormat>aab</AndroidPackageFormat>`

to the Example csproj, see if that helps.

**Comment by Varmod** [comment]
Thanks, that was the last missing piece. It's working now.

I'm also recieving message like this, but currently they don't seem to do any harm:
```
message : MSB4120: Item 'Assets' definition within target references itself via (qualified or unqualified) metadatum 'Filename'. This can lead to unintended expansion and cross-applying of pre-existing items.
message : MSB4120: Item 'Assets' definition within target references itself via (qualified or unqualified) metadatum 'Extension'. This can lead to unintended expansion and cross-applying of pre-existing items.
message : MSB4120: Item 'Assets' definition within target references itself via (qualified or unqualified) metadatum 'RecursiveDir'. This can lead to unintended expansion and cross-applying of pre-existing items.
```

**Comment by dellis1972** [comment]
can you provide a diagnostic build log? 

From the command line do a `dotnet build -bl` to get an `msbuild.binlog` file. Zip that up and attach it to this issue. It might be something I need to modify in the targets.

**Comment by Varmod** [comment]
Sure thing, here's a build of the example project. Only difference is that there are 2 more text files.
[msbuild.zip](https://github.com/infinitespace-studios/MauiAndroidAssetPackExample/files/13207854/msbuild.zip)

**Comment by dellis1972** [comment]
Fix via https://github.com/infinitespace-studios/MauiAndroidAssetPackExample/commit/9cd00fa439a28c9b9ac1908f491a9021d229d9ec. 

Just a slight change to the target.
